#!/bin/sh
# Author   : Luis Colorado <luiscoloradourcola@gmail.com>
# Date     : mié sep  9 15:08:40 EEST 2015
# Copyright: (C) 2019--2020 LUIS COLORADO.  All rights reserved.
# License  : BSD v2

file="NOTES.txt"
default_editor=vi
START_TS=`date +%s`
DATE=`LANG=C date -r ${START_TS}`
DIRECTORY=$(basename $(pwd))
SHA256='sha256'

tmp0="`mktemp`"
tmp1="`mktemp`"
tmp2="`mktemp`"
tmp3="`mktemp`"

SEP_LINE="-----------------------------------------------------------------------"

trap 'rm -f "${tmp0}" "${tmp1}" "${tmp2}" "${tmp3}"' EXIT

cat <<EOF >${tmp1}
# ..,....;....,....;....,....;....,....;....,....;....,...;....,....;
#       10        20        30        40        50       60        70
# Directory: $DIRECTORY
# Date: ${DATE} (${START_TS})
# This file is to be edited for a note to be included in
# the file ${file} in the current directory.  If not
# existent, it is created.
#
# Lines beginning with '#' char are comments and are
# eliminated after note is edited.
#
# This temporary file's name is ${tmp1}, and will be
# added, before eliminating all comment lines, with a
# timestamp and an empty line to the file ${file}
#       10        20        30        40        50       60        70
# ..,....;....,....;....,....;....,....;....,....;....,...;....,....;
EOF

if [ "${EDITOR}" ] && [ -x "${EDITOR}" ]
then
    "${EDITOR}" "${tmp1}"
else
    "${default_editor}" "${tmp1}"
fi

END_TS=`date +%s`
END_DATE=`LANG=C date -r ${END_TS}`
DURATION=`expr ${END_TS} - ${START_TS}`
DURATION_STR="${DURATION}s"

if [ "${DURATION}" -ge 60 ]
then
    DURATION_SEC=`expr ${DURATION} % 60`
    DURATION=`expr ${DURATION} / 60`
    DURATION_STR="${DURATION}m ${DURATION_SEC}s"
    if [ "${DURATION}" -ge 60 ]
    then
        DURATION_MIN=`expr ${DURATION} % 60`
        DURATION=`expr ${DURATION} / 60`
        DURATION_STR="${DURATION}h ${DURATION_STR}"
        if [ "${DURATION}" -ge 24 ]
        then
            DURATION_HR=`expr ${DURATION} % 24`
            DURATION=`expr ${DURATION} / 24`
            DURATION_STR="${DURATION}d ${DURATION_STR}"
        fi
    fi
fi

# eliminate comment lines.
sed '/^[ \t]*#/d;s/^/> /' "${tmp1}" > "${tmp2}"
if [ "0" -eq "`sed '/^> [ \t]*$/d' "${tmp2}" | wc -l`" ]
then
    # empty file
	echo "DIRECTORY=${DIRECTORY}" >&2
    echo "START_TS=${START_TS}" >&2
    echo "DATE=${DATE}" >&2
    echo "END_TS=${END_TS}" >&2
    echo "END_DATE=${END_DATE}" >&2
    echo "DURATION=${DURATION}" >&2
    echo "DURATION_STR=${DURATION_STR}" >&2
    echo "Aborting due to empty file" >&2
    exit 1
fi

# initialization of ${file} if not existent.
if [ \! -f "${file}" ]
then
    cat <<EOF >"${file}"
Created    : ${DATE}
File       : ${file}
EOF
    # "${SHA256}" <"${file}" >>"${file}"
    echo "${SEP_LINE}" >>"${file}"
fi

cat <<EOF - "${tmp2}" >"${tmp3}"
Directory  : ${DIRECTORY}
Start-date : ${DATE} (${START_TS})
End-date   : ${END_DATE} (${END_TS})
Report-time: ${DURATION_STR}

EOF

# "${SHA256}" <"${tmp3}" >>"${tmp3}"

cat "${tmp3}" - <<EOF >>"${file}"
${SEP_LINE}
EOF

# "${SHA256}" <"${file}" >>"${file}"
